version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - POSTGRESQL_PASSWORD=superpuper
  phppgadmin:
    image: docker.io/bitnami/phppgadmin:7
    environment:
      - DATABASE_HOST=postgresql
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - postgresql